### PR TITLE
float and double support

### LINKED ISSUE #25: How to set data type float
I'm not sure the way to set float as data type.  
My OAS3 yaml is defined some prameters as float.  

```
        location:
          type: object
          properties:
            longitude:
              type: number
              format: float
            latitude:
              type: number
              format: float
              example: 139.599194
```
However when creating proto file by *gnostic*, they are turned to int.  

```
message Location {
  int32 longitude = 1;

  int32 latitude = 2;
}
```

Please give some advices...

### PR DESCRIPTION
**Pull request by fideltak**
fixed #25

### CODE REVIEW

**Comment by fideltak** [comment]
@googlebot I signed it!

**Comment by LorenzHW** [comment]
@fideltak I hope it is ok for you that I used this PR to fix the broken CI. Please consent to the googlebot that you are OK with it.

Travis was using Go version 1.11, therefore test cases were failing. My commits update the version of Go to 1.13 for Travis. Additionally, there are minor refactoring changes.

**Comment by fideltak** [comment]
@googlebot I consent.

**Comment by LorenzHW** [comment]
@googlebot I consent.

**Review by noahdietz — COMMENTED** [review]
This looks fine to me, but can we add something to our test data to cover the new type support?

**Review by noahdietz — APPROVED** [review]

**Pull request merged**
